import { ContratoTag } from "@/types/contratos";

// Tags de sistema que são preenchidas automaticamente (Empresa e Cliente)
export const TAGS_SISTEMA: ContratoTag[] = [
  // --- Dados da Empresa Logada (Contratante) ---
  {
    id: 'sys-empresa-nome',
    nome_tag: '{{EMPRESA_NOME}}',
    descricao: 'Nome/Razão Social da Empresa Contratante.',
    origem_dado: 'tbl_clientes.nome',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-documento',
    nome_tag: '{{EMPRESA_DOCUMENTO}}',
    descricao: 'CPF ou CNPJ da Empresa Contratante.',
    origem_dado: 'tbl_clientes.documento',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-cpf',
    nome_tag: '{{EMPRESA_CPF}}',
    descricao: 'CPF da Empresa Contratante (se PF).',
    origem_dado: 'tbl_clientes.cpf',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-cnpj',
    nome_tag: '{{EMPRESA_CNPJ}}',
    descricao: 'CNPJ da Empresa Contratante (se PJ).',
    origem_dado: 'tbl_clientes.cnpj',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-rg',
    nome_tag: '{{EMPRESA_RG}}',
    descricao: 'RG da Empresa Contratante.',
    origem_dado: 'tbl_clientes.rg',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-endereco',
    nome_tag: '{{EMPRESA_ENDERECO}}',
    descricao: 'Logradouro e Número da Empresa Contratante.',
    origem_dado: 'tbl_clientes.endereco',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-numero',
    nome_tag: '{{EMPRESA_NUMERO}}',
    descricao: 'Número do Endereço da Empresa Contratante.',
    origem_dado: 'tbl_clientes.numero',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-complemento',
    nome_tag: '{{EMPRESA_COMPLEMENTO}}',
    descricao: 'Complemento do Endereço da Empresa Contratante.',
    origem_dado: 'tbl_clientes.complemento',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-bairro',
    nome_tag: '{{EMPRESA_BAIRRO}}',
    descricao: 'Bairro da Empresa Contratante.',
    origem_dado: 'tbl_clientes.bairro',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-cidade',
    nome_tag: '{{EMPRESA_CIDADE}}',
    descricao: 'Cidade da Empresa Contratante.',
    origem_dado: 'tbl_clientes.cidade',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-estado',
    nome_tag: '{{EMPRESA_ESTADO}}',
    descricao: 'Estado (UF) da Empresa Contratante.',
    origem_dado: 'tbl_clientes.estado',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-cep',
    nome_tag: '{{EMPRESA_CEP}}',
    descricao: 'CEP da Empresa Contratante.',
    origem_dado: 'tbl_clientes.cep',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-telefone',
    nome_tag: '{{EMPRESA_TELEFONE}}',
    descricao: 'Telefone da Empresa Contratante.',
    origem_dado: 'tbl_clientes.telefone',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-empresa-email',
    nome_tag: '{{EMPRESA_EMAIL}}',
    descricao: 'Email da Empresa Contratante.',
    origem_dado: 'tbl_clientes.email',
    criado_em: new Date().toISOString(),
  },

  // --- Dados do Cliente (Contratado - Tabela 'clientes') ---
  {
    id: 'sys-cliente-nome',
    nome_tag: '{{CLIENTE_NOME}}',
    descricao: 'Nome Fantasia / Nome Pessoal do Cliente Contratado.',
    origem_dado: 'clientes.nome',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-razao-social',
    nome_tag: '{{CLIENTE_RAZAO_SOCIAL}}',
    descricao: 'Razão Social do Cliente Contratado.',
    origem_dado: 'clientes.razao_social',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-nome-fantasia',
    nome_tag: '{{CLIENTE_NOME_FANTASIA}}',
    descricao: 'Nome Fantasia do Cliente Contratado.',
    origem_dado: 'clientes.nome_fantasia',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-documento',
    nome_tag: '{{CLIENTE_DOCUMENTO}}',
    descricao: 'CPF ou CNPJ do Cliente Contratado.',
    origem_dado: 'clientes.documento',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-cpf',
    nome_tag: '{{CLIENTE_CPF}}',
    descricao: 'CPF do Cliente Contratado.',
    origem_dado: 'clientes.cpf',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-cnpj',
    nome_tag: '{{CLIENTE_CNPJ}}',
    descricao: 'CNPJ do Cliente Contratado.',
    origem_dado: 'clientes.cnpj',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-rg',
    nome_tag: '{{CLIENTE_RG}}',
    descricao: 'RG do Cliente Contratado.',
    origem_dado: 'clientes.rg',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-email',
    nome_tag: '{{CLIENTE_EMAIL}}',
    descricao: 'Email do Cliente Contratado.',
    origem_dado: 'clientes.email',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-telefone',
    nome_tag: '{{CLIENTE_TELEFONE}}',
    descricao: 'Telefone Principal do Cliente Contratado.',
    origem_dado: 'clientes.telefone',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-telefone-fixo',
    nome_tag: '{{CLIENTE_TELEFONE_FIXO}}',
    descricao: 'Telefone Fixo do Cliente Contratado.',
    origem_dado: 'clientes.telefone_fixo',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-cep',
    nome_tag: '{{CLIENTE_CEP}}',
    descricao: 'CEP do Cliente Contratado.',
    origem_dado: 'clientes.cep',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-endereco',
    nome_tag: '{{CLIENTE_ENDERECO}}',
    descricao: 'Logradouro/Rua do Cliente Contratado.',
    origem_dado: 'clientes.endereco',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-numero',
    nome_tag: '{{CLIENTE_NUMERO}}',
    descricao: 'Número do Endereço do Cliente Contratado.',
    origem_dado: 'clientes.numero',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-complemento',
    nome_tag: '{{CLIENTE_COMPLEMENTO}}',
    descricao: 'Complemento do Endereço do Cliente Contratado.',
    origem_dado: 'clientes.complemento',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-bairro',
    nome_tag: '{{CLIENTE_BAIRRO}}',
    descricao: 'Bairro do Cliente Contratado.',
    origem_dado: 'clientes.bairro',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-cidade',
    nome_tag: '{{CLIENTE_CIDADE}}',
    descricao: 'Cidade do Cliente Contratado.',
    origem_dado: 'clientes.cidade',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-estado',
    nome_tag: '{{CLIENTE_ESTADO}}',
    descricao: 'Estado (UF) do Cliente Contratado.',
    origem_dado: 'clientes.estado',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-cliente-data-nascimento',
    nome_tag: '{{CLIENTE_DATA_NASCIMENTO}}',
    descricao: 'Data de Nascimento/Abertura do Cliente Contratado.',
    origem_dado: 'clientes.data_nascimento',
    criado_em: new Date().toISOString(),
  },
  
  // --- Dados do Usuário (Funcionário) ---
  {
    id: 'sys-usuario-nome',
    nome_tag: '{{USUARIO_NOME}}',
    descricao: 'Nome Completo do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.nome',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-cpf',
    nome_tag: '{{USUARIO_CPF}}',
    descricao: 'CPF do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.cpf',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-rg',
    nome_tag: '{{USUARIO_RG}}',
    descricao: 'RG do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.rg',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-nome-mae',
    nome_tag: '{{USUARIO_NOME_MAE}}',
    descricao: 'Nome da Mãe do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.nome_mae',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-nome-pai',
    nome_tag: '{{USUARIO_NOME_PAI}}',
    descricao: 'Nome do Pai do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.nome_pai',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-telefone',
    nome_tag: '{{USUARIO_TELEFONE}}',
    descricao: 'Telefone do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.telefone',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-cep',
    nome_tag: '{{USUARIO_CEP}}',
    descricao: 'CEP do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.cep',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-endereco',
    nome_tag: '{{USUARIO_ENDERECO}}',
    descricao: 'Logradouro/Rua do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.endereco',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-numero',
    nome_tag: '{{USUARIO_NUMERO}}',
    descricao: 'Número do Endereço do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.numero',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-complemento',
    nome_tag: '{{USUARIO_COMPLEMENTO}}',
    descricao: 'Complemento do Endereço do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.complemento',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-bairro',
    nome_tag: '{{USUARIO_BAIRRO}}',
    descricao: 'Bairro do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.bairro',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-cidade',
    nome_tag: '{{USUARIO_CIDADE}}',
    descricao: 'Cidade do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.cidade',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-estado',
    nome_tag: '{{USUARIO_ESTADO}}',
    descricao: 'Estado (UF) do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.estado',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-salario',
    nome_tag: '{{USUARIO_SALARIO}}',
    descricao: 'Salário Mensal do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.salario',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-horas-mensais',
    nome_tag: '{{USUARIO_HORAS_MENSAIS}}',
    descricao: 'Horas Mensais de Trabalho do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.horas_mensais',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-data-inicio-contrato',
    nome_tag: '{{USUARIO_DATA_INICIO_CONTRATO}}',
    descricao: 'Data de Início do Contrato do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.data_inicio_contrato',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-usuario-data-fim-contrato',
    nome_tag: '{{USUARIO_DATA_FIM_CONTRATO}}',
    descricao: 'Data de Fim do Contrato do Usuário/Funcionário.',
    origem_dado: 'tbl_usuarios.data_fim_contrato',
    criado_em: new Date().toISOString(),
  },
  
  // --- Tags de Assinatura (NOVAS) ---
  {
    id: 'sys-assinatura-cliente',
    nome_tag: '{{ASSINATURA_CLIENTE}}',
    descricao: 'Local para assinatura do Cliente/Contratado.',
    origem_dado: null,
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-assinatura-empresa',
    nome_tag: '{{ASSINATURA_EMPRESA}}',
    descricao: 'Local para assinatura da Empresa/Contratante.',
    origem_dado: null,
    criado_em: new Date().toISOString(),
  },
];

/**
 * Tags Financeiras Obrigatórias (Contas a Receber)
 */
export const TAGS_FINANCEIRAS_OBRIGATORIAS: ContratoTag[] = [
  {
    id: 'sys-valor-total',
    nome_tag: '{{VALOR_TOTAL_CONTRATO}}',
    descricao: 'Valor total do contrato (formatado em R$).',
    origem_dado: 'contas_receber.valor_total',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-valor-parcela',
    nome_tag: '{{VALOR_PARCELA}}',
    descricao: 'Valor de cada parcela (formatado em R$).',
    origem_dado: 'contas_receber.valor_parcela',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-numero-parcelas',
    nome_tag: '{{NUMERO_PARCELAS}}',
    descricao: 'Número total de parcelas/repetições.',
    origem_dado: 'contas_receber.numero_parcelas',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-primeiro-vencimento',
    nome_tag: '{{PRIMEIRO_VENCIMENTO}}',
    descricao: 'Data do primeiro vencimento (formatada).',
    origem_dado: 'contas_receber.data_vencimento',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'sys-data-emissao',
    nome_tag: '{{DATA_EMISSAO}}',
    descricao: 'Data de emissão do contrato (hoje).',
    origem_dado: 'contas_receber.data_emissao',
    criado_em: new Date().toISOString(),
  },
];

// TAGS_PADRAO agora é a combinação de todas as tags de sistema e financeiras
export const TAGS_PADRAO: ContratoTag[] = [...TAGS_SISTEMA, ...TAGS_FINANCEIRAS_OBRIGATORIAS];