
-- 1. Create a bucket for protocolos
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('protocolos', 'protocolos', true, 5242880, '{"image/jpeg","image/png","application/pdf","text/plain"}')
ON CONFLICT (id) DO NOTHING;

-- 2. Create the protocolos table
CREATE TABLE IF NOT EXISTS public.protocolos (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    cliente_id bigint NOT NULL,
    admin_id uuid,
    numero_protocolo text,
    status text DEFAULT 'Impresso'::text,
    img_protocolo text,
    nome_resp_recebimento text,
    data_recebimento timestamp with time zone,
    CONSTRAINT protocolos_pkey PRIMARY KEY (id),
    CONSTRAINT protocolos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.tbl_clientes (id) ON DELETE CASCADE
);

-- 3. Enable RLS
ALTER TABLE public.protocolos ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for protocolos
CREATE POLICY "Enable ALL for users based on admin_id" ON public.protocolos
AS PERMISSIVE FOR ALL
TO authenticated
USING ((auth.uid() = admin_id OR admin_id = get_admin_id_for_current_user()))
WITH CHECK ((auth.uid() = admin_id OR admin_id = get_admin_id_for_current_user()));

-- 5. Create the protocolo_files table
CREATE TABLE IF NOT EXISTS public.protocolo_files (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    protocolo_id bigint NOT NULL,
    file_name text,
    file_url text,
    CONSTRAINT protocolo_files_pkey PRIMARY KEY (id),
    CONSTRAINT protocolo_files_protocolo_id_fkey FOREIGN KEY (protocolo_id) REFERENCES public.protocolos (id) ON DELETE CASCADE
);

-- 6. Enable RLS for protocolo_files
ALTER TABLE public.protocolo_files ENABLE ROW LEVEL SECURITY;

-- 7. Create Policies for protocolo_files
CREATE POLICY "Enable ALL for users based on protocol admin_id" ON public.protocolo_files
AS PERMISSIVE FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM protocolos
    WHERE protocolos.id = protocolo_id AND (protocolos.admin_id = auth.uid() OR protocolos.admin_id = get_admin_id_for_current_user())
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM protocolos
    WHERE protocolos.id = protocolo_id AND (protocolos.admin_id = auth.uid() OR protocolos.admin_id = get_admin_id_for_current_user())
  )
);
