// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jqoirlswewggyppgvgnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxb2lybHN3ZXdnZ3lwcGd2Z252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTIxNzgsImV4cCI6MjA3MjU4ODE3OH0.73vN336GSU5zfCOuWvO_zIhg40KTVNhSS8UMhUxMc6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);